#' Uses the package 'here' to set the working directory to the correct one
setwd(here::here("bayesian-computation"))

#' Alternatively, you can do this by going on the bottom-right panel, selecting 
#' the tab "Files" (which is the default/first one), then navigate to 
#' "practicals", then "bayesian-computation" and then "R-files". Then click on 
#' the right-most button "More" and select from the slider menu 
#' "Set As Working Directory"
#' 
#' Or, you can do this in the R terminal by typing the command 
#' setwd("PATH-TO-YOUR-FOLDER")
#' The path changes depending on the operating system. In the case of the 
#' Binder Virtual Machine, this would be
#' setwd("~/practical/bayesian-computation/")
#' or in a more verbose way
#' setwd("/home/rstudio/practical/bayesian-computation/")
#' (note that '~' is a shortcut for the home folder '/home/rstudio', 
#' in this case)

# Creates the list of data
data=list(
a = 9.2, b = 13.8, # prior parameters
y = 15,            # number of successes
m = 20,            # number of trials
n = 40,            # future number of trials
ncrit = 25)        # critical value of future successes

# First, load the package 'R2jags' (instead of 'R2jags')
library(R2jags)

#' In the Binder VM, this is already installed, so you are good to go.
#' If you're doing this on your own machine, you must install first
#' jags and then in R run the following command:
#' install.packages("R2jags")
#' 
model = jags(
  data=data,
  parameters.to.save=c("y.pred","theta","P.crit"),
  inits=NULL,
  # The model file is define externally - using here::here ensures that we 
  # pick the correct full path to the model file
  model.file=here::here("bayesian-computation","drug-MCMC.txt"),
  n.chains=2,
  n.iter=5000,
  n.burnin=0,
  DIC=TRUE
)


# Visualise the results
print(model,digit=3)

# And uses bmhe functions to graphically show convergence etc
bmhe::traceplot(model,"theta")
bmhe::traceplot(model,"y.pred")

# Checks for autocorrelation
bmhe::acfplot(model)

# Plots the posterior distributions
bmhe::posteriorplot(model,plot="bar")


#' NB: R2jags stores the results generated by running the MCMC algorithm in a 
#' sub-object, called 'BUGSoutput'. So if you want to access the variables 
#' stored in there, you need to do something like
model$BUGSoutput$sims.matrix |> head()

#' Manually computes PSR (up to correction factor!) and n_eff using the 
#' simulations from the model. Use the first node
x=model$BUGSoutput$sims.array[,,1]

# Defines the relevant quantities
# Number of simulations (rows of x)
nsims=nrow(x)
# Number of chains (columsn of x)
nchains=ncol(x)
# Vector of variance for simulated values in each chain
sigma2.hat=apply(x,2,var)
# Vector of mean for simulated values in each chain
mu.hat=apply(x,2,mean)
W=mean(sigma2.hat)
B=nsims*var(mu.hat)

# Now can compute (approximated) PSR (Rhat) and neff
Rhat_approx=sqrt( (1/W) * ( ((nsims-1)/nsims) * W + ((nchains+1)/(nsims*nchains)) * B ))
neff=nchains * nsims * min((1/B)*(((nsims-1)/nsims) * W + B/nsims), 1)
